home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home"),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = (
    [
        path("", include(("home.urls", "home"), namespace="home")),
        path("polls/", include(("polls.urls", "polls"), namespace="polls")),
        path("admin/", admin.site.urls),
        path("user/", include(("user_app.urls", "user_app"), namespace="user_app")),
        path("accounts/", include("django.contrib.auth.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + debug_toolbar_urls()
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns

polls/urls.py
from django.urls import path
from . import views, validation_views


urlpatterns = [
    path("", views.home, name="home"),
    path("topic-detail/<int:topic_id>/", views.topic_detail, name="topic_detail"),
    path("random-topic-detail/", views.random_topic_detail, name="random_topic_detail"),
    path("modal/", views.render_modal, name="render_modal"),
]

htmx_patterns = [
    path("htmx/topics-search/", views.topics_search, name="topics_search"),
    path("htmx/add-topic/", views.add_topic, name="add_topic"),
    path("htmx/suggest-topic", views.suggest_topic, name="suggest_topic"),
    path("htmx/add-subject/", views.add_subject, name="add_subject"),
    path("htmx/sort-subjects/", views.sort_subjects, name="sort_subjects"),
    path("htmx/submit-ballot/", views.submit_ballot, name="submit_ballot"),
    path("htmx/load-subjects/", views.load_subjects, name="load_subjects"),
]

validation_patterns = [
    path("htmx/validate-topic/", validation_views.validate_topic, name="validate_topic"),
    path("htmx/validate-subject/", validation_views.validate_subject, name="validate_subject"),
    path(
        "htmx/validate-topic-suggestion/",
        validation_views.validate_topic_suggestion,
        name="validate_topic_suggestion",
    ),
]


urlpatterns += htmx_patterns
urlpatterns += validation_patterns

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# from django.http import HttpResponse
from polls.models import Topic
import random


# Create your views here.


def home(request):
    context = {}
    topics = list(Topic.objects.all())
    random.shuffle(topics)
    context["topics"] = topics[:25]
    context["total_extra"] = len(topics) - len(context["topics"])
    return render(request, "home/home.html", context=context)

polls/views.py
from django_htmx.http import (
    trigger_client_event,
    retarget,
    reswap,
    HttpResponseClientRedirect,
)
from django.shortcuts import render
from user_app.views import render_register_modal, render_login_modal

from django.urls import reverse
from .models import Topic, Subject, TopicOwner, Vote, Ranking
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect

from django_htmx.middleware import HtmxDetails

from django.utils import timezone


from django.db import IntegrityError


# Create your views here.
class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


MODAL_CONFIG = {
    # Pattern
    # "element-id": {"template": "path/to/template.html", "auth_required": True/False},
    # Auth not required
    "suggest-topic": {
        "template": "polls/modals/suggest-topic.html",
        "auth_required": False,
    },
    # Auth Required
    "new-topic": {"template": "polls/modals/new-topic.html", "auth_required": True},
    "edit-topic": {"template": "polls/modals/edit-topic.html", "auth_required": True},
    "new-subject": {"template": "polls/modals/new-subject.html", "auth_required": True},
}


def home(request: HtmxHttpRequest) -> HttpResponse:
    # authenticated users can see the new topic button, suggest topic button, and my topics
    # unauthenticated users can see the search bar, the public topics, and "find a random topic"
    context = {}
    context["public_topic_count"] = Topic.objects.filter(publicly_visible=True).count()
    return render(request, "polls/home.html", context=context)


def topics_search(request: HtmxHttpRequest) -> HttpResponse:
    context = {}
    context["topics"] = Topic.objects.filter(topic_text__icontains=request.POST.get("search"))

    return render(request, "polls/partials/topics-search.html", context)


def topic_detail(request, topic_id):
    """
    Topic detail view. A topic is the high level item. CSS/Javascript/Woodworking/Math

    Subject is the lower level item. CSS -> Flexbox, Grid, etc.
    Math --> Algebra, Geometry, etc.
    """

    context = {}
    user = request.user
    if user.is_anonymous:
        context["anonymous"] = True
    context["subjects"] = Subject.objects.filter(topic=topic_id).prefetch_related(
        "subjectlinks_set"
    )
    try:
        context["topic_owner"] = TopicOwner.objects.get(topic=topic_id).user.email
    except TopicOwner.DoesNotExist:
        context["topic_owner"] = "Unknown"
    context["topic"] = Topic.objects.get(id=topic_id)
    # context['newer_subjects'] = Subject.objects.filter(topic=topic_id, subjectscore__score__lt=10)

    return render(request, "polls/topic-detail.html", context=context)


def random_topic_detail(request):
    """
    randomly gets an ID to a topic, then redirects to the topic_detail view.
    """

    topic = Topic.objects.order_by("?").first()
    return HttpResponseRedirect(reverse("polls:topic_detail", args=[topic.id]))


def render_modal(request: HtmxHttpRequest) -> HttpResponse:
    trigger = request.htmx.trigger
    modal_config = MODAL_CONFIG.get(trigger)
    context = {}

    if not modal_config:
        return HttpResponse(status=404)

    if modal_config["auth_required"] and not request.user.is_authenticated:
        return render_login_modal(request)

    template = modal_config["template"]
    response = render(request, template, context)
    response = trigger_client_event(response, "openModal", after="swap")
    return response


def add_topic(request: HtmxHttpRequest) -> HttpResponse:
    if request.POST:
        topic = request.POST.get("topic")
        reference_link = request.POST.get("reference-link")
        print(request.POST)
        user = request.user

        try:
            topic, _ = Topic.objects.get_or_create(
                topic_text=topic, pub_date=timezone.now(), reference_link=reference_link
            )
        except IntegrityError:
            response = HttpResponse("Topic already exists", status=400)
            response = retarget(response, "#topic-error")
            return response

        topic_owner = TopicOwner.objects.get_or_create(user=user, topic=topic)

        if "btn-save-return" in request.POST:
            url = reverse("polls:topic_detail", args=[topic.id])
            response = HttpResponse(f"""<a class="topic" href="{url}">{ topic.topic_text }</a>""")
            response = reswap(response, "beforeend")

            response = retarget(response, "#topics__grid")
            response = trigger_client_event(response, "closeModal", after="swap")

            return response
        elif "btn-save-open" in request.POST:
            response = HttpResponseClientRedirect(reverse("polls:topic_detail", args=[topic.id]))
            return response


def suggest_topic(request: HtmxHttpRequest) -> HttpResponse:
    if request.POST:
        # TODO: Email the topic to the owner of the site
        # TODO add a message to the user that their suggestion has been submitted
        response = HttpResponse("Suggestion submitted")
        response = trigger_client_event(response, "closeModal", after="swap")
        return response


def add_subject(request: HtmxHttpRequest) -> HttpResponse:
    if request.POST:
        topic = Topic.objects.get(id=request.POST.get("topic"))
        subject_text = request.POST.get("subject")
        details = request.POST.get("details")

        subject = Subject.objects.create(
            topic=topic, subject_text=subject_text, details=details, pub_date=timezone.now()
        )

        if "btn-save-return" in request.POST:
            url = reverse("polls:topic_detail", args=[topic.id])
            response = HttpResponse(
                f"""<a class="subject" href="{url}">{ subject.subject_text }</a>"""
            )
            response = reswap(response, "beforeend")

            response = retarget(response, "#subjects__grid")
            response = trigger_client_event(response, "closeModal", after="swap")

            return response


def load_subjects(request: HtmxHttpRequest) -> HttpResponse:
    user = request.user
    community_list = request.GET.get("is-community-list", None)

    context = {}
    if community_list or user.is_anonymous:  # Checkbox is true or user is anonymous
        context["topic"] = Topic.objects.get(id=request.GET.get("topic"))
        context["subjects"] = context["topic"].subject_set.all()
        context["subjects"] = sorted(context["subjects"], key=lambda subject: subject.total_score)
        context["ignore_tag"] = "ignore-elements"

        return render(request, "polls/partials/subjects.html", context)
    else:
        try:
            context["topic"] = Topic.objects.get(id=request.GET.get("topic"))
            context["latest_vote"] = Vote.objects.filter(user=user, topic=context["topic"]).latest(
                "date_updated"
            )
            rankings = Ranking.objects.filter(vote=context["latest_vote"]).order_by("order")

            voted_subject_ids = [ranking.subject.id for ranking in rankings]
            context["subjects"] = [ranking.subject for ranking in rankings]
            voted_subject_ids = [ranking.subject.id for ranking in rankings]

            context["unvoted_subjects"] = context["topic"].subject_set.exclude(
                id__in=voted_subject_ids
            )
            context["ignore_tag"] = ""
        except Vote.DoesNotExist:
            # If the user has not voted before then do the following to render
            context["topic"] = Topic.objects.get(id=request.GET.get("topic"))
            context["subjects"] = context["topic"].subject_set.all()
            context["unvoted_subjects"] = context["topic"].subject_set.all()

    return render(request, "polls/partials/subjects.html", context)
    context = {}
    context["topic"] = Topic.objects.get(id=request.GET.get("topic"))
    context["subjects"] = context["topic"].subject_set.all()
    return render(request, "polls/partials/subjects.html", context)


def submit_ballot(vote, request: HtmxHttpRequest) -> HttpResponse:
    # This serves as when they hit the official submit button, it will save the order of the subjects
    now = timezone.now()
    vote.submitted = True
    vote.date_updated = now
    vote.save()

    return HttpResponse("")


def sort_subjects(request: HtmxHttpRequest) -> HttpResponse:
    # This serves as the in process state before submission so they can come back.

    # Check that the items being sorted are underneath the correct topic
    # This is a check that someone didn't change an input value to move an item to a different topic
    user = request.user
    if request.POST:
        topic = request.POST.get("topic")
        subjects = request.POST.getlist("subject")

        topic = Topic.objects.get(id=topic)
        subjects_json = [
            {"order": count, "subject": subject} for count, subject in enumerate(subjects, start=1)
        ]

        try:
            # TODO put in a process to check if that latest vote on the topic is equal to the currently being submitted/saved vote
            vote = Vote.objects.create(user=user, topic=topic)
            Ranking.objects.bulk_create(
                [
                    Ranking(vote=vote, order=ranking["order"], subject_id=ranking["subject"])
                    for ranking in subjects_json
                ]
            )
            if request.htmx.trigger_name == "save-ballot-btn":
                response = HttpResponse("Ballot Saved but not submitted")
            if request.htmx.trigger_name == "submit-ballot-btn":
                vote = Vote.objects.filter(user=user, topic=topic, submitted=False).latest(
                    "date_updated"
                )
                response = submit_ballot(vote, request)
            response = retarget(response, "#ballot-status")
            return response
        except Exception as e:
            print(e)

    return HttpResponse("")

polls/templates/polls/home.html
{% extends "base.html" %}

{% load static %}
{% block title %}Home{% endblock %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/polls/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/polls/partials/new-topic-modal.css' %}">

{% endblock %}


{% block content %}
    <h2>Topics</h2>
    
    <div class="search-container">
        <input type="text" id="search" placeholder="Search our {{public_topic_count}} public topics!"
        
        name="search"
        hx-post = "{% url 'polls:topics_search' %}" 
        hx-trigger="input changed delay:500ms, keyup[key=='Enter'], load"
        hx-target=".topics__grid"
        hx-indicator=".loader"
        {% comment %} 
        This is what loads in the topics from searching. It loads in topics-search.html
        This is done because A - it needs to be searched. B - It needs to render on load, but stream the results
        {% endcomment %}
        >
        <div class="loader htmx-indicator"></div>
    </div>
    <div class="buttons__container">
        {% if user.is_authenticated %}
        <button 
            class="button open-modal"
            id="new-topic"
            hx-get="{% url 'polls:render_modal' %}"
            hx-target="#modal-content"
            
            >Add New Topic</button>
        {% endif %}
        {% comment %}
        {% if user.is_authenticated %}
        <button 
            class="button open-modal"
            id="suggest-topic"
            hx-get="{% url 'polls:render_modal' %}"
            hx-target="#modal-content"
            
            >Suggest New Topic</button>
        {% endif %}
        {% endcomment %}
        <a class="button" href="{% url 'polls:random_topic_detail' %}">Find a Random Topic</a>
        {% if user.is_authenticated %}
            <button class="button" >My Topics</button>
        {% endif %}
    </div>

    <div id="topics__grid" class="topics__grid">
        {% comment %} Topics are displayed with partials/topics-search.html {% endcomment %}
    </div>


    

{% endblock %}

polls/templates/polls/htmx-example.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django + Htmx modal</title>
  {% comment %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% endcomment %}
</head>

<body>

  <h1>Django + HTMX Modal</h1>

  <button type="button" hx-get="{% url 'modal' %}" hx-swap="beforeend" hx-target="body"
    class="btn btn-primary btn-lg">Show Modal</button>

  <script src="https://unpkg.com/htmx.org@2.0.4"
    integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
    crossorigin="anonymous"></script>
    {% comment %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
    {% endcomment %}
</body>

</html>

polls/templates/polls/render-modal.html
{% comment %}
<style>
    .modal {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 600px;
        max-width: 100%;
        height: 400px;
        max-height: 100%;
        background-color: white;
    }
    .modal__header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        border-bottom: 1px solid #ccc;
        margin-bottom: 20px;
    }
    .modal__guts {
        
  /* cover the modal */
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  

  /* spacing as needed */
  padding: 20px 50px 20px 20px;


  /* let it scroll */
  overflow: auto;
    }
</style>
<!-- https://css-tricks.com/considerations-styling-modal/ -->
<div class="modal" id="modal">

<!-- things that don't scroll -->
<div class="modal__header">
    <h2>Modal Title</h2>
    <button aria-label="Close modal" hx-post="{% url 'polls:render_modal' %}" hx-swap="outerHTML" hx-target=".ballot__footer" class="close-button">X</button>
</div>

    <div class="modal__guts">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos incidunt officia temporibus dolores laborum minima alias neque similique animi illo. Amet quis mollitia placeat! Quos ut unde facilis enim numquam expedita autem nobis impedit, magni repellat a pariatur at delectus fugiat quia suscipit. Tenetur, doloribus animi sunt corrupti nulla amet consequuntur temporibus pariatur natus culpa adipisci consequatur debitis iusto magnam porro modi possimus? In dolore similique rem eos autem illo ad tempore esse doloremque. Aliquam, necessitatibus modi iusto officia debitis aliquid explicabo quo quos ratione commodi. Rem, incidunt dolorem blanditiis possimus assumenda corporis a rerum ut deserunt numquam necessitatibus maxime?
    </div>
</div>
{% endcomment %}

<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>This is the modal body</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

  

polls/templates/polls/render_modal.html
{% comment %}
<style>
    .modal {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 600px;
        max-width: 100%;
        height: 400px;
        max-height: 100%;
        background-color: white;
    }
    .modal__header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        border-bottom: 1px solid #ccc;
        margin-bottom: 20px;
    }
    .modal__guts {
        
  /* cover the modal */
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  

  /* spacing as needed */
  padding: 20px 50px 20px 20px;


  /* let it scroll */
  overflow: auto;
    }
</style>
<!-- https://css-tricks.com/considerations-styling-modal/ -->
<div class="modal" id="modal">

<!-- things that don't scroll -->
<div class="modal__header">
    <h2>Modal Title</h2>
    <button aria-label="Close modal" hx-post="{% url 'polls:render_modal' %}" hx-swap="outerHTML" hx-target="#modal" class="close-button">X</button>
</div>

    <div class="modal__guts">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos incidunt officia temporibus dolores laborum minima alias neque similique animi illo. Amet quis mollitia placeat! Quos ut unde facilis enim numquam expedita autem nobis impedit, magni repellat a pariatur at delectus fugiat quia suscipit. Tenetur, doloribus animi sunt corrupti nulla amet consequuntur temporibus pariatur natus culpa adipisci consequatur debitis iusto magnam porro modi possimus? In dolore similique rem eos autem illo ad tempore esse doloremque. Aliquam, necessitatibus modi iusto officia debitis aliquid explicabo quo quos ratione commodi. Rem, incidunt dolorem blanditiis possimus assumenda corporis a rerum ut deserunt numquam necessitatibus maxime?
    </div>
</div>

{% endcomment %}

<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>This is the modal body</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>