home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home"),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = (
    [
        path("", include(("home.urls", "home"), namespace="home")),
        path("polls/", include(("polls.urls", "polls"), namespace="polls")),
        path("admin/", admin.site.urls),
        path("user/", include(("user_app.urls", "user_app"), namespace="user_app")),
        path("accounts/", include("django.contrib.auth.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + debug_toolbar_urls()
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns

user_app/urls.py
from django.urls import path
from .views import (
    verify_user,
    send_test_email,
    login_user,
    register_user,
    logout_user,
    render_login_modal,
    render_register_modal,
)
from .validation_views import *

urlpatterns = [
    path("verify/<str:token>/", verify_user, name="verify_user"),
    path("send-test-email/", send_test_email, name="send_test_email"),
]

htmx_patterns = [
    path("htmx/login-user/", login_user, name="login_user"),
    path("htmx/register-user/", register_user, name="register_user"),
    path("htmx/logout-user/", logout_user, name="logout_user"),
    path("htmx/render-login-modal/", render_login_modal, name="render_login_modal"),
    path("htmx/render-register-modal/", render_register_modal, name="render_register_modal"),
]

validation_patterns = [
    path("htmx/user-registration-email/", user_registration_email, name="user_registration_email"),
    path(
        "htmx/user-registartion-pass/",
        user_registration_pass,
        name="user_registration_pass",
    ),
    path("htmx/validate-email/", validate_email, name="validate_email"),
    path("htmx/validate-password/", validate_password, name="validate_password"),
    path("htmx/validate-confirm-password/", validate_password, name="validate_confirm_password"),
]

urlpatterns += htmx_patterns
urlpatterns += validation_patterns

user_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils.crypto import get_random_string
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError(_("The Email field must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))

        return self.create_user(email, password, **extra_fields)

    def update_user_password(self, user, new_password):
        user.set_password(new_password)
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True, db_index=True)
    first_name = models.CharField(_("first name"), max_length=255, blank=True, null=True)
    last_name = models.CharField(_("last name"), max_length=255, blank=True, null=True)
    is_active = models.BooleanField(_("active"), default=True)
    is_staff = models.BooleanField(_("staff status"), default=False)
    is_superuser = models.BooleanField(_("superuser status"), default=False)
    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)
    is_verified = models.BooleanField(_("verified"), default=False)
    verification_token = models.CharField(
        _("verification token"), max_length=64, blank=True, null=True
    )
    token_expiration = models.DateTimeField(_("token expiration"), blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def generate_verification_token(self):
        self.verification_token = get_random_string(length=64)
        self.token_expiration = timezone.now() + timezone.timedelta(days=1)
        self.save()


# Use signals to handle non-critical updates asynchronously
@receiver(post_save, sender=CustomUser)
def update_last_login(sender, instance, **kwargs):
    # Update last_login or perform other non-critical operations
    pass

user_app/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import CustomUser


class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ("email", "first_name", "last_name", "is_staff", "is_active", "is_superuser")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class CustomUserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = (
            "email",
            "password",
            "first_name",
            "last_name",
            "is_staff",
            "is_active",
            "is_superuser",
        )

    def clean_password(self):
        return self.initial["password"]

user_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from .models import CustomUser
from django.conf import settings
from utils import timeit


from post_office import mail
import json


from django_htmx.http import (
    trigger_client_event,
    retarget,
    reswap,
    HttpResponseClientRedirect,
    HttpResponseLocation,
    push_url,
)
from django_htmx.middleware import HtmxDetails
import random
import string


class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


def send_test_email(request):
    mail.send(
        recipients=["timothymalahy@protonmail.com"],
        sender="donotreply@localhost.com",
        subject="sample",
        message=f"sample test",
        priority="now",
    )
    return HttpResponse("Email sent")


def send_verification_email(user):
    print("USER", user)
    token = user.generate_verification_token()
    print("TOKEN", token)
    print(user.verification_token)
    verification_link = f"{settings.SITE_URL}/user/verify/{user.verification_token}"
    mail.send(
        recipients=user.email,
        sender=f"donotreply@complexityindex.com",
        subject="Verify your account",
        message=f"Click the link to verify your account: {verification_link}",
    )


def verify_user(request, token):
    try:
        user = CustomUser.objects.get(verification_token=token, token_expiration__gt=timezone.now())
        user.is_verified = True
        user.verification_token = None
        user.token_expiration = None
        user.save()
        return HttpResponse("Your account has been verified.")
    except CustomUser.DoesNotExist:
        return HttpResponse("Verification link is invalid or has expired.")


def render_register_modal(request: HtmxHttpRequest) -> HttpResponse:
    def generate_random_email():
        domains = ["example.com", "test.com", "sample.org"]
        username = "".join(random.choices(string.ascii_lowercase + string.digits, k=10))
        domain = random.choice(domains)
        return f"{username}@{domain}"

    email = generate_random_email()
    request.POST = request.POST.copy()
    request.POST["email"] = email
    response = render(request, "user_app/partials/register-modal.html", {"email": email})
    response = trigger_client_event(response, "openModal", after="swap")
    return response


def render_login_modal(request: HtmxHttpRequest) -> HttpResponse:
    context = {}
    random_user = CustomUser.objects.order_by("?").first()
    context["email"] = random_user.email
    context["password"] = "abcdefgh12"
    response = render(request, "user_app/partials/login-modal.html", context=context)
    response = trigger_client_event(response, "openModal", after="swap")
    return response


@timeit.timeit
def login_user(request: HtmxHttpRequest) -> HttpResponse:
    email = request.POST.get("email")
    password = request.POST.get("password")
    user = authenticate(request, email=email, password=password)

    if user is not None:
        login(request, user)
        referrer = request.headers.get("Referer", "/")
        return HttpResponseClientRedirect(referrer)
    else:
        response = HttpResponse("Invalid login credentials", status=200)
        response = retarget(response, "#form-errors")
        return response


def logout_user(request) -> HttpResponse:
    logout(request)
    referrer = request.headers.get("Referer")
    return HttpResponseRedirect(referrer)


def register_user(request: HtmxHttpRequest) -> HttpResponse:
    """
    Errors are related to the form fields. Basically each input has a validation step that is found in validation_views.py
    After the form is validated, the user is created and the modal is closed.
    """
    response = HttpResponse("", status=200)
    errors = request.POST.get("errors")
    errors_response = []

    if errors:
        errors_dict = json.loads(errors)
        for key, value in errors_dict.items():
            if value:
                errors_response.append(value)
    if errors_response:
        errors_response.append("<strong>Please correct the errors above</strong>")
        response = HttpResponse("<br>".join(errors_response), status=200)
        response = retarget(response, "#form-errors")
        return response
    new_user = CustomUser.objects.create_user(
        email=request.POST.get("email"), password=request.POST.get("password")
    )
    new_user.first_name = request.POST.get("first-name")
    new_user.last_name = request.POST.get("last-name")
    new_user.save()

    send_verification_email(new_user)

    response = trigger_client_event(response, "closeModal", after="receive")
    return response

user_app/templates/user_app/partials/login-modal.html
{% comment %}https://docs.djangoproject.com/en/5.1/topics/auth/default/#how-to-log-a-user-in{% endcomment %}
{% load static %}

<script src="{% static 'js/htmx/extensions/preload.js' %}" defer></script>

<form 
hx-post="{% url 'user_app:login_user' %}" 
id="login-form" 
class="login-form"
hx-indicator="#modal-loader"
hx-ext="preload">
    {% csrf_token %}
    <div class="login-form__email">
        <label class="asterisk" for="email">Email</label>
        <input type="email" id="email" name="email" required {% if debug %} value="{{email}}" {% endif %}
        hx-post="{% url 'user_app:validate_email' %}"
        hx-trigger="input changed delay:250ms"
        hx-swap="innerHTML">
        <span id="email-error" class="error-message"></span>
    </div>
    <div class="login-form__password">
        <label class="asterisk" for="password">Password</label>
        <input type="password" id="password" name="password" required {% if debug %} value='{{password}}' {% endif %}
        hx-post="{% url 'user_app:validate_password' %}"
        hx-trigger="input changed"
        hx-swap="innerHTML">
        <span id="password-error" class="error-message"></span>
    </div>
    <span id="form-errors" class="error-message"></span>
    <div class="login-form__buttons">
        <button 
            class="button modal__button btn-login" 
            name="btn-login" 
            type="submit">
        Login </button>
        <button 
        class="button modal__button btn-register"
        name="btn-register" 
        type="button"
        hx-target="#modal-content"
        hx-get="{% url 'user_app:render_register_modal' %}"> Switch to Register Form</button>
        <button class="button modal__button btn-forgot-password" name="btn-forgot-password" type="button">Forgot Password</button>
    </div>

</form>

user_app/templates/user_app/partials/register-modal.html
{% comment %}https://docs.djangoproject.com/en/5.1/topics/auth/default/#how-to-log-a-user-in{% endcomment %}

<form hx-post="{% url 'user_app:register_user' %}" id="register-form" class="register-form"
hx-vals='js:{errors: getInner(["email-error", "password-error", "confirm-password-error"])}'
hx-indicator="#modal-loader"
>
    {% csrf_token %}
    <div class="register-form__email">
        <label class="asterisk" for="email">Email</label>
        <input type="email" id="email" name="email" required {% if debug %} value="{{email}}" {% endif %}
        hx-post="{% url 'user_app:user_registration_email' %}"
        hx-trigger="input changed delay:200ms"
        hx-swap="innerHTML">
        <span id="email-error" class="error-message"></span>
    </div>
    <div class="regsiter-from__first-name">
        <label for="first-name">First Name</label>
        <input type="text" id="first-name" name="first-name" {% if debug %} value="John" {% endif %}>
    </div>
    <div class="regsiter-from__last-name">
        <label for="last-name">Last Name</label>
        <input type="text" id="last-name" name="last-name" {% if debug %} value="Smith" {% endif %}>
    </div>
    <div class="register-form__password">
        <label class="asterisk" for="password">Password</label>
        <input type="password" id="password" name="password" required {% if debug %} value="abcdefgh12" {% endif %}
        hx-post="{% url 'user_app:user_registration_pass' %}"
        hx-trigger="input changed  delay:200ms"
        hx-swap="innerHTML">
        <span id="password-error" class="error-message"></span>
    </div>
    <div class="register-form__confirm-password">
        <label class="asterisk" for="confirm-password">Confirm Password</label>
        <input type="password" id="confirm-password" name="confirm-password" required {% if debug %} value="abcdefgh12" {% endif %}
        hx-post="{% url 'user_app:user_registration_pass' %}"
        hx-trigger="input changed  delay:200ms"
        hx-swap="innerHTML">
        <span id="confirm-password-error" class="error-message"></span>
    </div>
    <div class="register-form__buttons">
        <button class="button modal__button btn-register" name="btn-register" type="submit">Register</button>
        <button 
        class="button modal__button btn-login"
        name="btn-login" 
        type="button"
        hx-target="#modal-content"
        hx-get="{% url 'user_app:render_login_modal' %}">Switch to Login Form</button>
    </div>
    <span id="form-errors" class="error-message"></span>
</form>