home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home"),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = (
    [
        path("", include(("home.urls", "home"), namespace="home")),
        path("polls/", include(("polls.urls", "polls"), namespace="polls")),
        path("admin/", admin.site.urls),
        path("user/", include(("user_app.urls", "user_app"), namespace="user_app")),
        path("accounts/", include("django.contrib.auth.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + debug_toolbar_urls()
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns

user_app/urls.py
from django.urls import path
from .views import (
    verify_user,
    send_test_email,
    login_user,
    register_user,
    logout_user,
    render_login_modal,
    render_register_modal,
)
from .validation_views import *

urlpatterns = [
    path("verify/<str:token>/", verify_user, name="verify_user"),
    path("send-test-email/", send_test_email, name="send_test_email"),
]

htmx_patterns = [
    path("htmx/login-user/", login_user, name="login_user"),
    path("htmx/register-user/", register_user, name="register_user"),
    path("htmx/logout-user/", logout_user, name="logout_user"),
    path("htmx/render-login-modal/", render_login_modal, name="render_login_modal"),
    path("htmx/render-register-modal/", render_register_modal, name="render_register_modal"),
]

validation_patterns = [
    path("htmx/user-registration-email/", user_registration_email, name="user_registration_email"),
    path(
        "htmx/user-registartion-pass/",
        user_registration_pass,
        name="user_registration_pass",
    ),
    path("htmx/validate-email/", validate_email, name="validate_email"),
    path("htmx/validate-password/", validate_password, name="validate_password"),
    path("htmx/validate-confirm-password/", validate_password, name="validate_confirm_password"),
]

urlpatterns += htmx_patterns
urlpatterns += validation_patterns

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Complexity Index{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/login-modal.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
    
    
    
    <!-- jsDelivr :: Sortable :: Latest (https://www.jsdelivr.com/package/npm/sortablejs) -->
    <script src="{% static 'js/sortable.min.js' %}" async></script>
    

    <!-- HTMX and extensions -->
    {% load django_htmx %}
    <script src="{% static 'js/htmx/htmx.min.js' %}" defer></script>
    <script src="{% static 'js/htmx/extensions/sse.js' %}" defer></script>
    <script src="{% static 'js/htmx/extensions/response-targets.js' %}" defer></script>
    <script src="{% static 'js/htmx/extensions/debug.js' %}" defer></script>
    <script src="{% static 'js/htmx/extensions/remove-me.js' %}" defer></script>
    
    {% django_htmx_script %}

    {% block extrahead %}{% endblock %}
</head>
<body class="gradient-background" hx-ext="sse,  response-targets" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block header %}
    <header>
        
        <div class="default-header">
                <h1 class="default-header__h1"><a href="{% url 'home:home' %}#home">Complexity Index</a></h1>
                <nav class="default-header__default-nav">
                    <ul class="nav-list">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'polls:home' %}">See Topics</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}#home">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}#blog">Blog</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user_app:logout_user' %}">Logout</a></li>
                            {% comment %} TODO: Make this into an icon and dropdown? {% endcomment %}
                        {% else %}
                            <li class="nav-item"><a class="nav-link open-modal"
                                id="login"
                                hx-get="{% url 'user_app:render_login_modal' %}"
                                hx-target="#modal-content">Login</a></li>
                            <li class="nav-item"><a class="nav-link open-modal" 
                                id="register"
                                hx-get="{% url 'user_app:render_register_modal' %}"
                                hx-target="#modal-content">Register</a></li>
                        {% endif %}
                    </ul>
                </nav>
        </div>
        
    </header>

    {% endblock %}
    <main>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <dialog class="modal" id="modal">
            <div class="modal__header" id="modal__header">
                <div id="modal-loader" class="loader htmx-modal-indicator"></div>
                <button class="button modal__button" id="modalClose">X</button>
            </div>
            <div class="modal-content" id="modal-content"></div>
            
        </dialog>
    </main>
    <footer>
        <div class="footer-container">
            <p class="footer-container__copyright">&copy; 2025 Complexity Index</p>
        </div>
    </footer>
</body>

<script>
    const modal = document.getElementById('modal')
    const closeModal = document.getElementById('modalClose')
    
    closeModal.onclick = () => modal.close()

    document.body.addEventListener('closeModal', () => {
        /* Views.py need to return this in the trigger_client_event to close the modal */
        modal.close()
    })
    document.body.addEventListener('openModal', () => {
        /* Views.py need to return this in the trigger_client_event to open the modal */
        modal.showModal()
    })
</script>
<script src="{% static 'js/sweetalert.min.js' %}"></script>


<script>

    function getInner(ids) {
        const errors = {};
        if (Array.isArray(ids)) {
            ids.forEach(id => {
                const element = document.getElementById(id);
                if (element) {
                    errors[id] = element.innerHTML;
                }
            });
        } else {
            const element = document.getElementById(ids);
            if (element) {
                errors[ids] = element.innerHTML;
            }
        }
        return errors;
    }
</script>
<script>
    {% if debug %}
    if (typeof window.htmx !== "undefined") {
        htmx.on("htmx:afterSettle", function(detail) {
            if (
                typeof window.djdt !== "undefined"
                && detail.target instanceof HTMLBodyElement
            ) {
                djdt.show_toolbar();
            }
        });
    }
{% endif %}
</script>
{% block extra_scripts %}{% endblock %}
</html>